service:
  name: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  environment:
    AUCTION_TABLE_NAME: ${self:custom.AuctionsTable.name}
    AUCTION_TABLE_NAME_INDEX: ${self:custom.AuctionsTable.index}
  iamRoleStatements:
    - ${file(aws/iam/AuctionsTableAIM.yml):AuctionsTableAIM}

resources:
  Resources:
    AuctionsTable: ${file(aws/resources/AuctionsTable.yml):AuctionsTable}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auction
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: /auction/{id}/bid
  processAuction:
    handler: src/handlers/processAuction.handler
#    events:
#      - schedule: rate(1 minute)

custom:
  bundle:
    linting: false
  AuctionsTable:
    table: Mickael
    index: 'status-endingAt'
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
